theme: jekyll-theme-slate
title: Hipster Efficient Software Security and Privacy Workshop
description: Help developers, managers and project owners to reduce costs and improve the effectiveness of their software privacy and security.
